package json

import (
	"testing"

	"paste-go/pkg/schema"
)

func TestJSONParser_CanParse(t *testing.T) {
	p := NewJSONParser()

	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{"Valid Object", `{"a":1}`, true},
		{"Valid Array", `[{"a":1}]`, true},
		{"Invalid String", `not json`, false},
		{"Empty", ``, false},
		{"Loose Object", `  { "a": 1 }  `, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := p.CanParse(tt.content); got != tt.want {
				t.Errorf("CanParse() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestJSONParser_Parse(t *testing.T) {
	p := NewJSONParser()
	content := `{"user_name": "alice", "is_admin": true, "age": 30}`

	s, err := p.Parse(content)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	if s.Name != "AutoGenerated" {
		t.Errorf("Struct name = %s, want AutoGenerated", s.Name)
	}

	fields := map[string]schema.Kind{
		"UserName": schema.KindString,
		"IsAdmin":  schema.KindBool,
		"Age":      schema.KindInt,
	}

	if len(s.Fields) != len(fields) {
		t.Errorf("Got %d fields, want %d", len(s.Fields), len(fields))
	}

	for _, f := range s.Fields {
		wantKind, ok := fields[f.Name]
		if !ok {
			t.Errorf("Unexpected field: %s", f.Name)
			continue
		}
		if f.Kind != wantKind {
			t.Errorf("Field %s kind = %v, want %v", f.Name, f.Kind, wantKind)
		}
	}
}

func TestJSONParser_ParseNested(t *testing.T) {
	p := NewJSONParser()
	content := `{
  "user": {"id": 1, "profile": {"email": "a@b.com"}},
  "items": [{"sku": "s1", "qty": 2}],
  "tags": ["a", "b"]
}`

	s, err := p.Parse(content)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	user := findField(s, "User")
	if user == nil || user.Kind != schema.KindObject || user.Nested == nil {
		t.Fatalf("user field not parsed as nested object")
	}
	profile := findField(user.Nested, "Profile")
	if profile == nil || profile.Kind != schema.KindObject || profile.Nested == nil {
		t.Fatalf("profile field not parsed as nested object")
	}

	items := findField(s, "Items")
	if items == nil || items.Kind != schema.KindArray || items.Nested == nil {
		t.Fatalf("items field not parsed as array of objects")
	}
	if findField(items.Nested, "Sku") == nil {
		t.Fatalf("items nested struct missing Sku")
	}

	tags := findField(s, "Tags")
	if tags == nil || tags.Kind != schema.KindArray {
		t.Fatalf("tags field not parsed as array")
	}
}

func findField(s *schema.Struct, name string) *schema.Field {
	for i := range s.Fields {
		if s.Fields[i].Name == name {
			return &s.Fields[i]
		}
	}
	return nil
}
