package json

import (
	"paste-go/pkg/schema"
	"testing"
)

func TestJSONParser_CanParse(t *testing.T) {
	p := NewJSONParser()

	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{"Valid Object", `{"a":1}`, true},
		{"Valid Array", `[{"a":1}]`, true},
		{"Invalid String", `not json`, false},
		{"Empty", ``, false},
		{"Loose Object", `  { "a": 1 }  `, true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := p.CanParse(tt.content); got != tt.want {
				t.Errorf("CanParse() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestJSONParser_Parse(t *testing.T) {
	p := NewJSONParser()
	content := `{"user_name": "alice", "is_admin": true, "age": 30}`

	s, err := p.Parse(content)
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}

	if s.Name != "AutoGenerated" {
		t.Errorf("Struct name = %s, want AutoGenerated", s.Name)
	}

	fields := map[string]schema.Kind{
		"UserName": schema.KindString,
		"IsAdmin":  schema.KindBool,
		"Age":      schema.KindFloat, // encoding/json unmarshals numbers to float64
	}

	if len(s.Fields) != len(fields) {
		t.Errorf("Got %d fields, want %d", len(s.Fields), len(fields))
	}

	for _, f := range s.Fields {
		wantKind, ok := fields[f.Name]
		if !ok {
			t.Errorf("Unexpected field: %s", f.Name)
			continue
		}
		if f.Kind != wantKind {
			t.Errorf("Field %s kind = %v, want %v", f.Name, f.Kind, wantKind)
		}
	}
}
